# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
