# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-23 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_auto_20180923_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteforcharacter',
            name='is_active',
        ),
    ]
